body:
  - attributes:
      description: If any of these required steps are not taken, we may not be able to review your issue. Help us to help you!
      label: RFC Checklist
      options:
        - label: I have [searched for related issues](https://github.com/JoshuaKGoldberg/package-json-validator/issues?q=is%3Aissue) and found none that matched my issue.
          required: true
    type: checkboxes
  - attributes:
      description: Please provide details about your proposal.
      label: Overview
    type: textarea
    validations:
      required: true
  - attributes:
      description: How long should this RFC remain open for feedback? This should be no less than 6 weeks from the publishing date.
      label: This RFC will remain open until
      placeholder: YYYY-MM-DD
    type: input
description: Request feedback from the community on a significant change to the project.

labels:
  - "type: rfc"
name: 💬 RFC
title: "💬 RFC: <short description of the proposal>"
